# Generated by Django 4.2.7 on 2023-11-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDemanda', models.CharField(max_length=255)),
                ('descricaoDemanda', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('urgente', 'Urgente'), ('maxima', 'Máxima')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], max_length=20)),
                ('prazo', models.DateField()),
                ('dataDeCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataDeEncerramento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tituloDemanda'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloMensagem', models.CharField(max_length=40, verbose_name='Titulo')),
                ('conteudo', models.CharField(max_length=250, verbose_name='Conteúdo da Mensagem')),
            ],
        ),
    ]
