# Generated by Django 4.2.7 on 2023-11-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDemanda', models.CharField(max_length=40, verbose_name='Nome')),
                ('descricaoDemanda', models.CharField(max_length=200, verbose_name='Descrição')),
                ('prioridade', models.CharField(max_length=30, verbose_name='Prioridade')),
            ],
        ),
    ]
