# Generated by Django 4.2.7 on 2023-12-10 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LabDevSoftware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['prazo', 'dataDeCriacao']},
        ),
        migrations.AddField(
            model_name='demanda',
            name='atribuido_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demanda',
            name='encaminhar_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_encaminhadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
