# Generated by Django 4.2.7 on 2023-11-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabDevSoftware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['prazo', 'dataDeCriacao']},
        ),
    ]
