# Generated by Django 4.2.7 on 2023-12-14 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LabDevSoftware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['prazo', 'dataDeCriacao']},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['tituloMensagem']},
        ),
        migrations.AddField(
            model_name='demanda',
            name='atribuido_a',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demanda',
            name='encaminhar_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_encaminhadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloTarefa', models.CharField(max_length=40, verbose_name='Titulo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUÍDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('atribuido_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabDevSoftware.demanda')),
            ],
            options={
                'ordering': ['tituloTarefa'],
            },
        ),
    ]
 