# Generated by Django 4.2.7 on 2023-12-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabDevSoftware', '0002_alter_demanda_options_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
    ]
