# Generated by Django 4.2.7 on 2023-12-14 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LabDevSoftware', '0002_alter_demanda_options_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='atribuido_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('urgente', 'Urgente'), ('maxima', 'Máxima')], default='Baixa', max_length=20),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='Pendente', max_length=20),
        ),
    ]
